Fmt: internal::basic_buffer< T > Class Template Reference
internal::basic_buffer< T > Class Template Reference abstract
A contiguous memory buffer with an optional growing ability.
#include <core.h>
Public Types
typedef T value_type
typedef const T & const_reference
Public Member Functions
T * begin () FMT_NOEXCEPT
T * end () FMT_NOEXCEPT
std::size_t size () const FMT_NOEXCEPT
Returns the size of this buffer.
std::size_t capacity () const FMT_NOEXCEPT
Returns the capacity of this buffer.
T * data () FMT_NOEXCEPT
Returns a pointer to the buffer data.
const T * data () const FMT_NOEXCEPT
Returns a pointer to the buffer data.
void resize (std::size_t new_size)
Resizes the buffer.
void clear ()
Clears this buffer.
void reserve (std::size_t new_capacity)
Reserves space to store at least capacity elements.
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
Appends data to the end of the buffer.
T & operator[] (std::size_t index)
const T & operator[] (std::size_t index) const
Protected Member Functions
basic_buffer (std::size_t sz) FMT_NOEXCEPT
basic_buffer (T *p=FMT_NULL, std::size_t sz=0, std::size_t cap=0) FMT_NOEXCEPT
void set (T *buf_data, std::size_t buf_capacity) FMT_NOEXCEPT
Sets the buffer data and capacity.
virtual void grow (std::size_t capacity)=0
Increases the buffer capacity to hold at least capacity elements.
Private Member Functions
basic_buffer (const basic_buffer &)=delete
void operator= (const basic_buffer &)=delete
Private Attributes
T * ptr_
std::size_t size_
std::size_t capacity_
Detailed Description
template<typename T>
class internal::basic_buffer< T >
A contiguous memory buffer with an optional growing ability.
Member Function Documentation
append()
template<typename T > template<typename U > template FMT_API void internal::basic_buffer< T >::append (const U * begin, const U * end)
Appends data to the end of the buffer.
Referenced by basic_printf_context< OutputIt, Char, ArgFormatter >::format().
capacity()
template<typename T> std::size_t internal::basic_buffer< T >::capacity () const inline
Returns the capacity of this buffer.
clear()
template<typename T> void internal::basic_buffer< T >::clear () inline
Clears this buffer.
data() [1/2]
template<typename T> T* internal::basic_buffer< T >::data () inline
Returns a pointer to the buffer data.
data() [2/2]
template<typename T> const T* internal::basic_buffer< T >::data () const inline
Returns a pointer to the buffer data.
grow()
template<typename T> virtual void internal::basic_buffer< T >::grow (std::size_t capacity) protected pure virtual
Increases the buffer capacity to hold at least capacity elements.
Implemented in basic_memory_buffer< T, SIZE, Allocator >, basic_memory_buffer< Char >, and internal::container_buffer< Container >.
Referenced by internal::basic_buffer< Char >::reserve().
reserve()
template<typename T> void internal::basic_buffer< T >::reserve (std::size_t new_capacity) inline
Reserves space to store at least capacity elements.
Referenced by internal::basic_buffer< Char >::resize().
resize()
template<typename T> void internal::basic_buffer< T >::resize (std::size_t new_size) inline
Resizes the buffer.
If T is a POD type new elements may not be initialized.
set()
template<typename T> void internal::basic_buffer< T >::set (T * buf_data, std::size_t buf_capacity) inline protected
Sets the buffer data and capacity.
size()
template<typename T> std::size_t internal::basic_buffer< T >::size () const inline
Returns the size of this buffer.
The documentation for this class was generated from the following files:
include/fmt/core.h
include/fmt/format.h
src/fmt/format.cc